[package]
name = "TVpTB"
version = "0.1.0"
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.7.9"
hyper = "1.5.1"
serde = "1.0.215"
serde_json = "1.0.133"
tokio = "1.42.0"
tower = "0.5.1"
